{% set name = "wannier90io" %}
{% set version = "0.1.0b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wannier90io-{{ version }}.tar.gz
  sha256: 7b43d0cdcfdca5f3a0ce67b8605fde13c0afbfefb2319bae2f192b2189732c7d

build:
  entry_points:
    - w90io = wannier90io.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - numpy
    - pydantic

test:
  imports:
    - wannier90io
  commands:
    - pip check
    - w90io --help
  requires:
    - pip

about:
  summary: A Python library for Wannier90 I/O
  home: https://github.com/jimustafa/wannier90io-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
